### ISSUE TITLE
Dreamhack Summer replays

### ISSUE THREAD

**Issue by StanczakDominik** [ZephyrBlu/sc2-replay-analysis#1]
Hey,

Looking forward to seeing what comes out of this :)

I'm not sure if this is in scope, but Dreamhack just posted reps from the entire Summer circuit:

https://drive.google.com/drive/folders/1lOYMZR-BwqE4Lha6upOZyuvbOeJ42HAl

Might come in handy! :)

Cheers!

**Comment by StanczakDominik** [comment]
Closed by 75984ed

**Comment by ZephyrBlu** [comment]
@StanczakDominik I guess you noticed that I added them :). I haven't forgotten about your articles btw, I've just been busy lately :(.

**Comment by StanczakDominik** [comment]
I did press Watch on the repo :laughing: I hope that doesn't make me a stalker. *Cold is the void* etc etc.

> I've just been busy lately :(

Who hasn't? No worries! :smiley:
